### ISSUE TITLE
username is not unset upon exit

### ISSUE THREAD

**Issue by csperlich** [stefprez/database_project#14]
when i hit exit and go to the welcom page, the username is unset, In my branch i'm also unsetting the cart, however, when i go to the manage cart page as an unregistered user, it loads the cart for the last user i was logged in as and the username session variable is again set.

**Comment by csperlich** [comment]
To see what I mean, put print_r($_SESSION) statement at the top of welcome.php and shopping_cart.php. log in, put some items in a cart, hit an exit button, then enter as an unregistered user, then navigate to the shopping_cart.php page.

**Comment by csperlich** [comment]
think i almost got it, since we never included php_tools.php on the welcome.php page, it didn't know how to unset the variable.

**Comment by stefprez** [comment]
Awesome. I'll be back in about half in hour, but let me know if you need anything when I get back!

**Comment by csperlich** [comment]
Got it!
