### ISSUE TITLE
Adding to cart from search_results page

### ISSUE THREAD

**Issue by csperlich** [stefprez/database_project#3]
currently, as a logged in user, only 1 item can be added to the cart, and that item must be the very first item in the search result list.

**Comment by stefprez** [comment]
Having a tough time with this one. I suspect it has something to do with the creation of the Add To Cart buttons, but I'm not sure. A second pair of eyes would be great.

**Comment by csperlich** [comment]
I'll take a look at the code

**Comment by csperlich** [comment]
It's because the <form action="" method="POST> tag  at line 109 is outside
of the loop generating the addToCart buttons.

The fix:
change _<form action="" method="Post> *to *print '__<form action=""
method="Post>';_

and move it to right above this :print '<input type="submit" class="button"
value="Add To Cart"/>';
at line 120

**Comment by stefprez** [comment]
That did it! Issue is fixed, and being pushed up now.
