### ISSUE TITLE
logging out/exiting 3-B.com

### ISSUE THREAD

**Issue by csperlich** [stefprez/database_project#4]
clicking the exit 3-B.com button on any page doesn't unset the $_SESSION['username'] variable, so any time a user tries to exit, and then comes back in, they are really the same user unless they close their browser or log in as a different user. This is not the end of the world but is a little annoying for testing the non-logged in cart-management stuff. The solution! when a user clicks any exit 3-b.com button, we must unset($_SESSION['username']) and then redirect to the welcome.php page.

**Comment by stefprez** [comment]
This has been fixed on the search.php and search_result.php pages.

**Comment by csperlich** [comment]
<form action="welcome.php" method="post">
                    <input type="submit" name="exit" value="EXIT 3-B.com<?php unset($_SESSION['username']); ?>">
                </form>

The above doesn't unset the session variable, it just changes the value of the exit button. Instead, we just need to check for the "exit" value to be set on the welcome page, and unset the session variable there... I'm on it.

**Comment by stefprez** [comment]
Sounds great. I wasn't positive that would do it, and my methods of testing it weren't very robust either. Thanks for taking care of that.
