### ISSUE TITLE
Disable Proceed To Checkout Button if Shopping Cart is empty

### ISSUE THREAD

**Issue by csperlich** [stefprez/database_project#5]
If there are no items in the cart, we should disable the proceed to checkout button.

**Comment by stefprez** [comment]
This would require checking the contents of the shopping cart, which because of the way we handle it with either the session variable cart or the database, is mildly complex. I'm marking this as lower priority.

**Comment by stefprez** [comment]
Working on this now.

**Comment by csperlich** [comment]
wrote a function to get the number of items in a cart and put it in php_tools.php
search_results.php now displays number of items in cart and disables proceed_to_checkout button if there are no items in the cart.
