### ISSUE TITLE
No Buttons at Bottom of Search Results Box with a search that returns no results

### ISSUE THREAD

**Issue by csperlich** [stefprez/database_project#7]
if a search returns no results, no buttons are displayed at the bottom of the search results box

**Comment by stefprez** [comment]
I'm not seeing this. Either it has been fixed, or there is something I'm not doing correctly to recreate the bug.

**Comment by csperlich** [comment]
Ah, it's when we search on Publisher, the value for $_GET['serachon'] was 'Publisher', but it needed to be 'name' to match the ddl
