### ISSUE TITLE
Blank cart entry after adding an item to the cart

### ISSUE THREAD

**Issue by stefprez** [stefprez/database_project#9]
Happens when both the user is logged in or not. The blank entry cannot be deleted.

**Comment by csperlich** [comment]
Please describe this more. I'm not sure how to duplicate this.

**Comment by stefprez** [comment]
Whenever I go to the shopping cart, there is an entry that says "By: " "Price: " under book description, and in the price column, the price is $0. When I click the delete button, nothing happens.

**Comment by csperlich** [comment]
Hmm, I can't seem to recreate this....

**Comment by stefprez** [comment]
This may just be from all the mucking around I've done, and have added some garbage entry into the database or session variable cart. I'd say don't worry about it if it's not coming up for you.

**Comment by csperlich** [comment]
okay, let's leave this one open though

**Comment by stefprez** [comment]
This has disappeared for me now. I'm going to close it, and will reopen it if it reappears and I can figure out how to reproduce it.

**Comment by stefprez** [comment]
AHAH! That wasn't very long lived. It has to do with navigating from the reviews page back to the search results page. It adds an empty item to the cart there. I'm going to try and figure this out, but I sense it might be tricky, since it has to do with the passing of POST and GET variables, which I'm not super confident about.

**Comment by csperlich** [comment]
I think the fix hear is to check if you came from the reviews page, and only do add to cart if:

if ($_SERVER["REQUEST_METHOD"] == "POST" && !come_from_review_page) {
        addToCart($_POST['isbn']);
}

Maybe something like that?

**Comment by stefprez** [comment]
I found an easier fix. Just made the button function identically to the browser back button! :) It's been fixed a while ago. Just forgot to close this issue again.
